name = "Dirac3"
uuid = "6e1d72ef-e149-4f5c-9c69-bc0273b92dbc"
authors = ["Pedro Maciel Xavier <mail@pedro.ϵλ>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
QUBODrivers = "a3f166f7-2cd3-47b6-9e1e-6fbfe0449eb0"
QUBOTools = "60eb5b62-0a39-4ddc-84c5-97d2adff9319"

[compat]
LinearAlgebra = "1.11.0"
MathOptInterface = "1.35.2"
PythonCall = "0.9.24"
QUBODrivers = "0.3.3"
QUBOTools = "0.10.1"
