name = "Dirac3"
uuid = "6e1d72ef-e149-4f5c-9c69-bc0273b92dbc"
authors = ["Pedro Maciel Xavier <mail@pedro.ϵλ>"]
version = "0.1.0"

[deps]
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[compat]
MathOptInterface = "1.35.2"
