name = "QCIOpt"
uuid = "6e1d72ef-e149-4f5c-9c69-bc0273b92dbc"
authors = ["Pedro Maciel Xavier <mail@pedro.ϵλ>"]
version = "0.1.0"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
CondaPkg = "=0.2.24"
LinearAlgebra = "1.11.0"
MathOptInterface = "1.35.2"
PythonCall = "0.9.24"
